title: myakupa
iconURL: assets/test.png
theme: deneme

# for a clean URL
permalink: :slug

social:
  twitter: m_yakupa
  github: myakupa

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
